-- USED_GOODS_BOARD와 USED_GOODS_USER 테이블에서
-- 완료된 중고 거래의 총금액이 70만 원 이상인 
-- 사람의 회원 ID, 닉네임, 총거래금액을 조회하는 SQL문을 작성해주세요. 
-- 결과는 총거래금액을 기준으로 오름차순 정렬해주세요.

SELECT USED_GOODS_USER.USER_ID, USED_GOODS_USER.NICKNAME, sum(USED_GOODS_BOARD.PRICE) as TOTAL_SALES
from USED_GOODS_BOARD join USED_GOODS_USER on USED_GOODS_BOARD.WRITER_ID = USED_GOODS_USER.USER_ID
where USED_GOODS_BOARD.STATUS = 'DONE'
group by USED_GOODS_USER.USER_ID
having sum(USED_GOODS_BOARD.PRICE) >= 700000
order by sum(USED_GOODS_BOARD.PRICE)