-- 코드를 작성해주세요

-- 부모의 형질을 모두 보유한 where GENOTYPE & (select GENOTYPE from ECOLI_DATA where ID = PARENT_ID) > 0
-- 대장균의 ID(ID), 대장균의 형질(GENOTYPE), 부모 대장균의 형질(PARENT_GENOTYPE)을 출력하는 SQL 문을 작성해주세요.  select ID, GENOTYPE, PARENT_GENOTYPE
-- 이때 결과는 ID에 대해 오름차순 정렬해주세요. order by ID

-- 직계부모만 검사
-- 부모의 GENOTYPE을 추출해서, & 연산 결과가 0보다 큼

# SELECT ID, GENOTYPE, 
#        (SELECT GENOTYPE FROM ECOLI_DATA P WHERE P.ID = E.PARENT_ID) AS PARENT_GENOTYPE
# FROM ECOLI_DATA E
# WHERE GENOTYPE & (SELECT GENOTYPE FROM ECOLI_DATA P WHERE P.ID = E.PARENT_ID) = 
#       (SELECT GENOTYPE FROM ECOLI_DATA P WHERE P.ID = E.PARENT_ID)
# ORDER BY ID;

-- CE : CHILD ECOLI
-- PE : PARENT ECOLI
SELECT CE.ID, CE.GENOTYPE, PE.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA CE JOIN ECOLI_DATA PE ON CE.PARENT_ID = PE.ID
WHERE (CE.GENOTYPE & PE.GENOTYPE) = PE.GENOTYPE -- CE와 PE의 GENOTYPE의 비트마스크 &연산 결과와 PE의 GENOTYPE이 동일한 경우
ORDER BY CE.ID;