-- 상반기 동안 각 아이스크림 성분 타입과 성분 타입에 대한 아이스크림의 총주문량을  
-- 총주문량이 작은 순서대로 조회하는 SQL 문을 작성해주세요. 
-- 이때 총주문량을 나타내는 컬럼명은 TOTAL_ORDER로 지정해주세요.

# SELECT ICECREAM_INFO.INGREDIENT_TYPE, sum(FIRST_HALF.TOTAL_ORDER) as TOTAL_ORDER
# from FIRST_HALF join ICECREAM_INFO on FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
# group by ICECREAM_INFO.INGREDIENT_TYPE
# order by sum(FIRST_HALF.TOTAL_ORDER) asc;

SELECT  II.INGREDIENT_TYPE AS INGREDIENT_TYPE, SUM(FH.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF FH JOIN ICECREAM_INFO II ON FH.FLAVOR = II.FLAVOR
GROUP BY II.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC
